stages:
  data_ingestion:
    cmd: python src/Emotion_Detector/pipeline/stage01_data_ingestion.py
    deps: 
      - src/Emotion_Detector/pipeline/stage01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/test
      - artifacts/data_ingestion/train
      - artifacts/data_ingestion/raw_data/data.zip

  data_preprocessing:
    cmd: python src/Emotion_Detector/pipeline/stage02_data_preprocessing.py
    deps: 
      - src/Emotion_Detector/pipeline/stage02_data_preprocessing.py
      - configs/config.yaml
      - params.yaml
      - artifacts/data_ingestion/test
      - artifacts/data_ingestion/train

    outs:
      - artifacts/data_preprocessing/train_tfrecords
      - artifacts/data_preprocessing/test_tfrecords