CLASS_NAMES : ["angry", "disgust", "fear", "happy", "neutral", "sad", "surprise"]

RANDOM_SEED : 22

BATCH_SIZE : 32
IMAGE_SIZE : 256
LEARNING_RATE : 0.001
EPOCHS : 50
DROPOUT_RATE : 0.0
REGULARIZATION_RATE : 0.0
N_FILTERS : 6
KERNAL_SIZE : 3
N_STRIDES : 1
POOL_SIZE : 2
N_DENSE_1 : 100
N_DENSE_2 : 10
NUM_CLASSES : 7
SHUFFLE : True
TRAIN_NUM_SHARDS : 10
TEST_NUM_SHARDS : 5
RESNET_EPOCH : 25
RESNET_TRAIN_BATCH: 4

EN_DENSE_1: 1024
EN_DENSE_2: 128
INCLUDE_TOP: False
EN_EPOCH: 60
EN_BATCH_SIZE: 32

RANDOM_ROTATION_LEFT_FACTOR : -0.025
RANDOM_ROTATION_RIGHT_FACTOR : 0.025
RANDOM_FLIP_MODE : horizontal
RANDOMTRANSLATION_HEIGHT_FACTOR_LEFT : -0.1
RANDOMTRANSLATION_HEIGHT_FACTOR_RIGHT : 0.1
RANDOMTRANSLATION_WIDTH_FACTOR_LEFT : -0.1
RANDOMTRANSLATION_WIDTH_FACTOR_RIGHT : 0.1
RANDOM_ZOOM_FACTOR : 0.2