artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.dl.dropboxusercontent.com/s/skptyhjlrubpvgq/fer2013_zipped.zip?dl=0
  local_data_dir: artifacts/data_ingestion/raw_data
  local_data_file: artifacts/data_ingestion/raw_data/data.zip
  unzip_dir: artifacts/data_ingestion