artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.dl.dropboxusercontent.com/s/skptyhjlrubpvgq/fer2013_zipped.zip?dl=0
  local_data_dir: artifacts/data_ingestion/raw_data
  local_data_file: artifacts/data_ingestion/raw_data/data.zip
  unzip_dir: artifacts/data_ingestion

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  train_dir: artifacts/data_ingestion/train
  val_dir: artifacts/data_ingestion/test
  train_tf_records_dir: artifacts/data_preprocessing/train_tfrecords
  test_tf_records_dir: artifacts/data_preprocessing/test_tfrecords
  train_tf_records_file_path: 'artifacts/data_preprocessing/train_tfrecords/shard_{:02d}.tfrecord'
  test_tf_records_file_path: 'artifacts/data_preprocessing/test_tfrecords/shard_{:02d}.tfrecord'

model_training:
  root_dir: artifacts/model_training
  checkpoints_callback_dir: artifacts/model_training/model_checkpoints
  tensorboard_log_dir: artifacts/model_training/tensorboard_log_dir
  model_history_dir : artifacts/model_training/model_history
  model_dir : artifacts/model_training/model
  model_file_path : artifacts/model_training/model.h5
  checkpoints_file_path: artifacts/model_training/model_callbacks/model_{epoch:02d}.ckpt
  model_history_file_path :  artifacts/model_training/model_history/history.json
  train_tf_records_file_path: 'artifacts/data_preprocessing/train_tfrecords/shard_{:02d}.tfrecord'
  test_tf_records_file_path: 'artifacts/data_preprocessing/test_tfrecords/shard_{:02d}.tfrecord'